function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    kappa=((1/params(4)-1+params(5))/(params(3)*params(2)))^(1/(params(3)-1));
    ys_(2)=params(2)*(1-params(3))*kappa^params(3)/(params(2)*(1-params(3))*kappa^params(3)+params(1)*(params(2)*kappa^params(3)-params(5)*kappa));
    ys_(3)=kappa*ys_(2);
    ys_(4)=params(2)*kappa^params(3)*ys_(2);
    ys_(1)=(params(2)*kappa^params(3)-params(5)*kappa)*ys_(2);
    ys_(5)=params(5)*ys_(3);
    % Auxiliary equations
end
